name: Deploy to GitHub Pages
on:
  push:
    branches: ["12-pelican-website-poc"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "./.github/workflows/github_pages.yml"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "staticWebsite/publishconf.py"
  