name: Run simulation

on: 
    workflow_dispatch:
      inputs:
        branch_name:
            description: 'Branch name for simulation run'
            required: true
            default: 'develop'


jobs:
    notebooks:
        runs-on: ubuntu-latest
        steps:
            - name: Run notebooks
              uses: ..github/workflows/notebook_run.yml

    simulation:
        runs-on: ubuntu-latest
        needs: notebooks
        env:
          SIMULATION_OUTPUTS_PATH: outputs/simulation_results/
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                ref: ${{ inputs.branch_name }}

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Download notebook output data
              uses: actions/download-artifact@v2
              with:
                  name: notebook-outputs
                  path: outputs/tables

            - name: Run simulation
              run: |
                  python -m  src.main

            - name: Store simulation outputs
            # 
              uses: actions/upload-artifact@v3
              with:
              # upload all of 'outputs' directory
              # upload notebooks as html
                path: |
                  ${{ env.SIMULATION_OUTPUTS }}
                    
                # name the artifact
                name: simulation-outputs

                

